/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ButtonIcon: typeof import('./src/components/ButtonIcon.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    Message: typeof import('primevue/message')['default']
    Pet3D: typeof import('./src/components/Pet3D.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubWindowLayout: typeof import('./src/components/SubWindowLayout.vue')['default']
  }
}
